paths = {'Group1': {'material': ['stimuli/Group1/material/stairsA_camA_granularA__stairsB_camB_granularA__stairsB_camB_granularB.mp4',
                                 'stimuli/Group1/material/cubeA_camA_liquidA__cubeB_camB_liquidA__cubeB_camB_liquidB.mp4',
                                 'stimuli/Group1/material/freeShapeA_camA_nonrigidA__freeShapeB_camB_nonrigidA__freeShapeB_camB_nonrigidB.mp4',
                                 'stimuli/Group1/material/boxA_camA_granularA__boxB_camB_granularB__boxB_camB_granularB.mp4'],
                    'shape': ['stimuli/Group1/shape/stairsA_camA_granularA__stairsA_camB_layout__stairsB_camB_layout.mp4',
                              'stimuli/Group1/shape/stairsB_camB_granularA__stairsA_camA_layout__stairsB_camA_layout.mp4',
                              'stimuli/Group1/shape/cubeA_camA_liquidA__cubeA_camB_layout__cubeB_camB_layout.mp4',
                              'stimuli/Group1/shape/cubeB_camB_liquidA__cubeB_camA_layout__cubeB_camA_layout.mp4',
                              'stimuli/Group1/shape/freeShapeA_camA_nonrigidA__freeShapeA_camB_layout__freeShapeB_camB_layout.mp4',
                              'stimuli/Group1/shape/freeShapeB_camB_nonrigidA__freeShapeB_camA_layout__freeShapeB_camA_layout.mp4',
                              'stimuli/Group1/shape/boxA_camA_granularA__boxA_camB_layout__boxB_camB_layout.mp4',
                              'stimuli/Group1/shape/boxB_camB_granularA__boxB_camA_layout__boxB_camA_layout.mp4']},
         'Group2': {'material': ['stimuli/Group2/material/stairsA_camA_liquidA__stairsB_camB_liquidB__stairsB_camB_liquidB.mp4',
                                 'stimuli/Group2/material/cubeA_camA_nonrigidA__cubeB_camB_nonrigidB__cubeB_camB_nonrigidB.mp4',
                                 'stimuli/Group2/material/freeShapeA_camA_granularA__freeShapeB_camB_granularB__freeShapeB_camB_granularB.mp4',
                                 'stimuli/Group2/material/boxA_camA_liquidA__boxB_camB_liquidA__boxB_camB_liquidB.mp4'],
                    'shape': ['stimuli/Group2/shape/stairsA_camA_liquidA__stairsA_camB_layout__stairsB_camB_layout.mp4',
                              'stimuli/Group2/shape/stairsB_camB_liquidA__stairsA_camA_layout__stairsB_camA_layout.mp4',
                              'stimuli/Group2/shape/cubeA_camA_nonrigidA__cubeA_camB_layout__cubeB_camB_layout.mp4',
                              'stimuli/Group2/shape/cubeB_camB_nonrigidA__cubeB_camA_layout__cubeB_camA_layout.mp4',
                              'stimuli/Group2/shape/freeShapeA_camA_granularA__freeShapeA_camB_layout__freeShapeB_camB_layout.mp4',
                              'stimuli/Group2/shape/freeShapeB_camB_granularA__freeShapeA_camA_layout__freeShapeB_camA_layout.mp4',
                              'stimuli/Group2/shape/boxA_camA_liquidA__boxA_camB_layout__boxB_camB_layout.mp4',
                              'stimuli/Group2/shape/boxB_camB_liquidA__boxA_camA_layout__boxB_camA_layout.mp4']},
         'Group3': {'material': ['stimuli/Group3/material/stairsA_camA_nonrigidA__stairsB_camB_nonrigidB__stairsB_camB_nonrigidB.mp4',
                                 'stimuli/Group3/material/cubeA_camA_granularA__cubeB_camB_granularB__cubeB_camB_granularB.mp4',
                                 'stimuli/Group3/material/freeShapeA_camA_liquidA__freeShapeB_camB_liquidA__freeShapeB_camB_liquidB.mp4',
                                 'stimuli/Group3/material/boxA_camA_nonrigidA__boxB_camB_nonrigidB__boxB_camB_nonrigidB.mp4'],
                    'shape': ['stimuli/Group3/shape/stairsA_camA_nonrigidA__stairsB_camB_layout__stairsB_camB_layout.mp4',
                              'stimuli/Group3/shape/stairsB_camB_nonrigidA__stairsB_camA_layout__stairsB_camA_layout.mp4',
                              'stimuli/Group3/shape/cubeA_camA_granularA__cubeB_camB_layout__cubeB_camB_layout.mp4',
                              'stimuli/Group3/shape/cubeB_camB_granularA__cubeA_camA_layout__cubeB_camA_layout.mp4',
                              'stimuli/Group3/shape/freeShapeA_camA_liquidA__freeShapeA_camB_layout__freeShapeB_camB_layout.mp4',
                              'stimuli/Group3/shape/freeShapeB_camB_liquidA__freeShapeB_camA_layout__freeShapeB_camA_layout.mp4',
                              'stimuli/Group3/shape/boxA_camA_nonrigidA__boxB_camB_layout__boxB_camB_layout.mp4',
                              'stimuli/Group3/shape/boxB_camB_nonrigidA__boxA_camA_layout__boxB_camA_layout.mp4']}}
