var paths = {'Group1': {'material': ['stimuli/Group1/material/stairs_granular.mp4',
                                     'stimuli/Group1/material/cube_liquid.mp4',
                                     'stimuli/Group1/material/freeShape_nonrigid.mp4',
                                     'stimuli/Group1/material/box_granular.mp4'],
                        'shape': ['stimuli/Group1/shape/stairs_granularB.mp4',
                                  'stimuli/Group1/shape/stairs_granularA.mp4',
                                  'stimuli/Group1/shape/cube_liquidB.mp4',
                                  'stimuli/Group1/shape/cube_liquidA.mp4',
                                  'stimuli/Group1/shape/freeShape_nonrigidB.mp4',
                                  'stimuli/Group1/shape/freeShape_nonrigidA.mp4',
                                  'stimuli/Group1/shape/box_granularB.mp4',
                                  'stimuli/Group1/shape/box_granularA.mp4']},
             'Group2': {'material': ['stimuli/Group2/material/stairs_liquid.mp4',
                                     'stimuli/Group2/material/cube_nonrigid.mp4',
                                     'stimuli/Group2/material/freeShape_granular.mp4',
                                     'stimuli/Group2/material/box_liquid.mp4'],
                        'shape': ['stimuli/Group2/shape/stairs_liquidB.mp4',
                                  'stimuli/Group2/shape/stairs_liquidA.mp4',
                                  'stimuli/Group2/shape/cube_nonrigidB.mp4',
                                  'stimuli/Group2/shape/cube_nonrigidA.mp4',
                                  'stimuli/Group2/shape/freeShape_granularB.mp4',
                                  'stimuli/Group2/shape/freeShape_granularA.mp4',
                                  'stimuli/Group2/shape/box_liquidB.mp4',
                                  'stimuli/Group2/shape/box_liquidA.mp4']},
             'Group3': {'material': ['stimuli/Group3/material/stairs_nonrigid.mp4',
                                     'stimuli/Group3/material/cube_granular.mp4',
                                     'stimuli/Group3/material/freeShape_liquid.mp4',
                                     'stimuli/Group3/material/box_nonrigid.mp4'],
                        'shape': ['stimuli/Group3/shape/stairs_nonrigidB.mp4',
                                  'stimuli/Group3/shape/stairs_nonrigidA.mp4',
                                  'stimuli/Group3/shape/cube_granularB.mp4',
                                  'stimuli/Group3/shape/cube_granularA.mp4',
                                  'stimuli/Group3/shape/freeShape_liquidB.mp4',
                                  'stimuli/Group3/shape/freeShape_liquidA.mp4',
                                  'stimuli/Group3/shape/box_nonrigidB.mp4',
                                  'stimuli/Group3/shape/box_nonrigidA.mp4']}}
