paths = {
    "Group1": {
        "material": ["stimuli_rerun_exp1/Group1/material/boxA_camA_granularA__boxB_camB_granularB__boxB_camB_granularA.mp4", "stimuli_rerun_exp1/Group1/material/cubeA_camA_liquidA__cubeB_camB_liquidB__cubeB_camB_liquidA.mp4", "stimuli_rerun_exp1/Group1/material/stairsA_camA_nonrigidA__stairsB_camB_nonrigidA__stairsB_camB_nonrigidB.mp4", "stimuli_rerun_exp1/Group1/material/freeShapeA_camA_granularA__freeShapeB_camB_granularB__freeShapeB_camB_granularA.mp4", "stimuli_rerun_exp1/Group1/material/crossA_camA_liquidA__crossB_camB_liquidA__crossB_camB_liquidB.mp4", "stimuli_rerun_exp1/Group1/material/blobA_camA_nonrigidA__blobB_camB_nonrigidA__blobB_camB_nonrigidB.mp4"],
        "shape": ["stimuli2/Group1/shape/boxA_camA_granularA__boxA_camB_layout__boxB_camB_layout.mp4", "stimuli2/Group1/shape/boxB_camB_granularA__boxC_camA_layout__boxB_camA_layout.mp4", "stimuli2/Group1/shape/cubeA_camA_liquidA__cubeB_camB_layout__cubeA_camB_layout.mp4", "stimuli2/Group1/shape/cubeB_camB_liquidA__cubeC_camA_layout__cubeB_camA_layout.mp4", "stimuli2/Group1/shape/stairsA_camA_nonrigidA__stairsA_camB_layout__stairsB_camB_layout.mp4", "stimuli2/Group1/shape/stairsB_camB_nonrigidA__stairsC_camA_layout__stairsB_camA_layout.mp4", "stimuli2/Group1/shape/freeShapeA_camA_granularA__freeShapeB_camB_layout__freeShapeA_camB_layout.mp4", "stimuli2/Group1/shape/freeShapeB_camB_granularA__freeShapeB_camA_layout__freeShapeC_camA_layout.mp4", "stimuli2/Group1/shape/crossA_camA_liquidA__crossB_camB_layout__crossA_camB_layout.mp4", "stimuli2/Group1/shape/crossB_camB_liquidA__crossC_camA_layout__crossB_camA_layout.mp4", "stimuli2/Group1/shape/blobA_camA_nonrigidA__blobB_camB_layout__blobA_camB_layout.mp4", "stimuli2/Group1/shape/blobB_camB_nonrigidA__blobC_camA_layout__blobB_camA_layout.mp4"]
    },
    "Group2": {
        "material": ["stimuli_rerun_exp1/Group2/material/boxA_camA_liquidA__boxB_camB_liquidB__boxB_camB_liquidA.mp4", "stimuli_rerun_exp1/Group2/material/cubeA_camA_nonrigidA__cubeB_camB_nonrigidB__cubeB_camB_nonrigidA.mp4", "stimuli_rerun_exp1/Group2/material/stairsA_camA_granularA__stairsB_camB_granularB__stairsB_camB_granularA.mp4", "stimuli_rerun_exp1/Group2/material/freeShapeA_camA_liquidA__freeShapeB_camB_liquidB__freeShapeB_camB_liquidA.mp4", "stimuli_rerun_exp1/Group2/material/crossA_camA_nonrigidA__crossB_camB_nonrigidA__crossB_camB_nonrigidB.mp4", "stimuli_rerun_exp1/Group2/material/blobA_camA_granularA__blobB_camB_granularA__blobB_camB_granularB.mp4"],
        "shape": ["stimuli2/Group2/shape/boxA_camA_liquidA__boxB_camB_layout__boxA_camB_layout.mp4", "stimuli2/Group2/shape/boxB_camB_liquidA__boxB_camA_layout__boxC_camA_layout.mp4", "stimuli2/Group2/shape/cubeA_camA_nonrigidA__cubeB_camB_layout__cubeA_camB_layout.mp4", "stimuli2/Group2/shape/cubeB_camB_nonrigidA__cubeB_camA_layout__cubeC_camA_layout.mp4", "stimuli2/Group2/shape/stairsA_camA_granularA__stairsA_camB_layout__stairsB_camB_layout.mp4", "stimuli2/Group2/shape/stairsB_camB_granularA__stairsB_camA_layout__stairsC_camA_layout.mp4", "stimuli2/Group2/shape/freeShapeA_camA_liquidA__freeShapeA_camB_layout__freeShapeB_camB_layout.mp4", "stimuli2/Group2/shape/freeShapeB_camB_liquidA__freeShapeC_camA_layout__freeShapeB_camA_layout.mp4", "stimuli2/Group2/shape/crossA_camA_nonrigidA__crossB_camB_layout__crossA_camB_layout.mp4", "stimuli2/Group2/shape/crossB_camB_nonrigidA__crossC_camA_layout__crossB_camA_layout.mp4", "stimuli2/Group2/shape/blobA_camA_granularA__blobB_camB_layout__blobA_camB_layout.mp4", "stimuli2/Group2/shape/blobB_camB_granularA__blobC_camA_layout__blobB_camA_layout.mp4"]
    },
    "Group3": {
        "material": ["stimuli_rerun_exp1/Group3/material/boxA_camA_nonrigidA__boxB_camB_nonrigidA__boxB_camB_nonrigidB.mp4", "stimuli_rerun_exp1/Group3/material/cubeA_camA_liquidA__cubeB_camB_liquidA__cubeB_camB_liquidB.mp4", "stimuli_rerun_exp1/Group3/material/stairsA_camA_granularA__stairsB_camB_granularA__stairsB_camB_granularB.mp4", "stimuli_rerun_exp1/Group3/material/freeShapeA_camA_nonrigidA__freeShapeB_camB_nonrigidA__freeShapeB_camB_nonrigidB.mp4", "stimuli_rerun_exp1/Group3/material/crossA_camA_liquidA__crossB_camB_liquidA__crossB_camB_liquidB.mp4", "stimuli_rerun_exp1/Group3/material/blobA_camA_granularA__blobB_camB_granularA__blobB_camB_granularB.mp4"],
        "shape": ["stimuli2/Group3/shape/boxA_camA_nonrigidA__boxB_camB_layout__boxA_camB_layout.mp4", "stimuli2/Group3/shape/boxB_camB_nonrigidA__boxC_camA_layout__boxB_camA_layout.mp4", "stimuli2/Group3/shape/cubeA_camA_liquidA__cubeB_camB_layout__cubeA_camB_layout.mp4", "stimuli2/Group3/shape/cubeB_camB_liquidA__cubeB_camA_layout__cubeC_camA_layout.mp4", "stimuli2/Group3/shape/stairsA_camA_granularA__stairsB_camB_layout__stairsA_camB_layout.mp4", "stimuli2/Group3/shape/stairsB_camB_granularA__stairsC_camA_layout__stairsB_camA_layout.mp4", "stimuli2/Group3/shape/freeShapeA_camA_nonrigidA__freeShapeA_camB_layout__freeShapeB_camB_layout.mp4", "stimuli2/Group3/shape/freeShapeB_camB_nonrigidA__freeShapeC_camA_layout__freeShapeB_camA_layout.mp4", "stimuli2/Group3/shape/crossA_camA_liquidA__crossB_camB_layout__crossA_camB_layout.mp4", "stimuli2/Group3/shape/crossB_camB_liquidA__crossC_camA_layout__crossB_camA_layout.mp4", "stimuli2/Group3/shape/blobA_camA_granularA__blobA_camB_layout__blobB_camB_layout.mp4", "stimuli2/Group3/shape/blobB_camB_granularA__blobB_camA_layout__blobC_camA_layout.mp4"]
    }
}